### ISSUE TITLE
Use ITensors to compute the adiabatic gap

### ISSUE THREAD

**Issue by GiggleLiu** [Rose-max111/QuantumAdiabaticAnnealing.jl#8]
Ref:
1. https://queracomputing.github.io/Bloqade.jl/dev/tutorials/2.adiabatic/main/
2. https://github.com/ITensor/ITensors.jl
3. Ebadi, S., Keesling, A., Cain, M., Wang, T.T., Levine, H., Bluvstein, D., Semeghini, G., Omran, A., Liu, J.-G., Samajdar, R., Luo, X.-Z., Nash, B., Gao, X., Barak, B., Farhi, E., Sachdev, S., Gemelke, N., Zhou, L., Choi, S., Pichler, H., Wang, S.-T., Greiner, M., Vuletić, V., Lukin, M.D., 2022. Quantum optimization of maximum independent set using Rydberg atom arrays. Science 376, 1209–1215. https://doi.org/10.1126/science.abo6587
4. Cai, Z., Liu, J., 2018. Approximating quantum many-body wave functions using artificial neural networks. Phys. Rev. B 97, 035116. https://doi.org/10.1103/PhysRevB.97.035116

**Comment by Rose-max111** [comment]
already used ITensors@DMRG & CUDA.jl to compute adiabadic energy gap
